services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  frontend:
    build: ./react-admin
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: